# Importing  important  requirement

In [1]:
import pandas as  pd
import  numpy as np
import  matplotlib as plt 
import  seaborn as sns

In [38]:
import requests
import  csv
import json
import os
import re

# Getting API

In [65]:

# ⚠️ Put your NEW API key here
API_KEY = "7c8eca4ce6msh5db3313e36dae02p1b8723jsndcd477ef3bb4"
headers = {
    "Content-Type": "application/json",
    "X-RapidAPI-Key": API_KEY,
    "X-RapidAPI-Host": "instagram120.p.rapidapi.com"
}

post_url = "https://instagram120.p.rapidapi.com/api/instagram/posts"

all_posts = []   # ✅ VERY IMPORTANT (define first)
max_id = ""

for _ in range(10):   # 10 pages (~100+ posts)
    payload = {
        "username": "indiancricketteam",
        "maxId": max_id
    }

    response = requests.post(post_url, json=payload, headers=headers)
    data = response.json()

    posts = data.get("result", {}).get("edges", [])
    all_posts.extend(posts)

    max_id = data.get("result", {}).get("page_info", {}).get("end_cursor", "")

    if not max_id:
        break

print("Total posts collected:", len(all_posts))
# -------------------------
# 2️⃣ Process Posts
# -------------------------

for post in posts:
    node = post.get("node", {})

    post_id = node.get("id")
    username = node.get("owner", {}).get("username", "")

    # 🔹 FIX: Proper caption extraction
    caption_data = node.get("caption", "")

    if isinstance(caption_data, dict):
        caption = caption_data.get("text", "")
    else:
        caption = caption_data or ""

    # 🔹 FIX: Proper comments extraction
    comment_count= node.get("comments_count", 0)

    if isinstance(comment_count, dict):
        comment_count = comment_count.get("count", 0)
    else:
        comment_count = comment_count or 0

    # 🔹 Extract Hashtags
    hashtags = re.findall(r"#\w+", caption)

    # 🔹 Extract Mentions
    mentions = re.findall(r"@\w+", caption)

    print("\n==============================")
    print("Post ID:", post_id)
    print("Username:", username)
    print("Caption:", caption)
    print("Hashtags:", hashtags)
    print("Mentions:", mentions)
    print("comments:", comment_count)

Total posts collected: 120

==============================
Post ID: 3827747288501184594_2091666763
Username: indiancricketteam
Caption: When the captain calls, you answer 👌

🎥 From comeback to World Cup impact, ft. Mohd. Siraj 😎

#TeamIndia | #MenInBlue | #T20WorldCup | #INDvUSA | @mohammedsirajofficial
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: ['@mohammedsirajofficial']
comments: 0

==============================
Post ID: 3827433518691881452_2091666763
Username: indiancricketteam
Caption: Painting the ground with his masterful shot-making 🎨👏

One word for Captain Surya Kumar Yadav's match-winning knock? 👇

#TeamIndia | #MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827430289933428701_2091666763
Username: indiancricketteam
Caption: A captain’s knock to start the campaign 🫡

For his match-winning 84* (49), Surya Kumar Yadav is the Player of the Match as #TeamIndia begin the #T20WorldCup with a win! 👏

#MenInBlue | #INDvUSA
Hashtags: ['#TeamIndia', '#T20WorldCup', '#MenInBlue', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827428604007789663_2091666763
Username: indiancricketteam
Caption: A comprehensive victory ✌️

#TeamIndia are off the mark in the #T20WorldCup in fine fashion 👌👌

They win the #INDvUSA contest by 2⃣9⃣ runs 🙌

#MenInBlue
Hashtags: ['#TeamIndia', '#T20WorldCup', '#INDvUSA', '#MenInBlue']
Mentions: []
comments: 0

==============================
Post ID: 3827426905717605199_376525195
Username: icc
Caption: Mohammed Siraj wraps it up in Mumbai as India begin their quest to defend the #T20WorldCup title with a win 👊

Tournament broadcast details in our bio 📺
Hashtags: ['#T20WorldCup']
Mentions: []
comments: 0

==============================
Post ID: 3827419769864015347_2091666763
Username: indiancricketteam
Caption: #TeamIndia continue to chip away at the wickets 🥳

Arshdeep Singh with his 2⃣nd wicket 😎

Tilak Varma with the catch 👏

#MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827414274562431057_2091666763
Username: indiancricketteam
Caption: 2️⃣ in 2️⃣ for Axar Patel ✌️

#TeamIndia in control as we head into the final phase!

#MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827404635674336850_2091666763
Username: indiancricketteam
Caption: There's another breakthrough ☝️

🔝 work by Ishan Kishan behind the stumps as Varun Chakaravarthy strikes 🕸️

Wicket No. 4⃣ 👏

#TeamIndia | #MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827391828803213350_376525195
Username: icc
Caption: Arshdeep Singh gave India an early breakthrough to dismiss USA skipper Monank Patel 👊

#T20WorldCup broadcast details in our bio 📺
Hashtags: ['#T20WorldCup']
Mentions: []
comments: 0

==============================
Post ID: 3827388979922920451_376525195
Username: icc
Caption: Rohit Sharma. Wankhede. #T20WorldCup Trophy in hand. Fans roaring. Iconic ❤️

Don’t miss any action from the tournament. Broadcast details in bio 🔗
Hashtags: ['#T20WorldCup']
Mentions: []
comments: 0

==============================
Post ID: 3827389515141316940_2091666763
Username: indiancricketteam
Caption: A successful powerplay 🙌

#TeamIndia pick 3⃣ wickets 👏

#MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

==============================
Post ID: 3827381664376993793_2091666763
Username: indiancricketteam
Caption: Up and running with the ball 👊

Mohd. Siraj and Arshdeep Singh strike early to give #TeamIndia a perfect start!

#MenInBlue | #T20WorldCup | #INDvUSA
Hashtags: ['#TeamIndia', '#MenInBlue', '#T20WorldCup', '#INDvUSA']
Mentions: []
comments: 0

Save Data in  CSV form

In [68]:
with open("instagram_dataset.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)

    writer.writerow([
        "post_id",
        "username",
        "caption",
        "hashtags",
        "mentions",
        "likes",
        "comment_count"
    ])

    for post in all_posts:   # ✅ IMPORTANT CHANGE
        node = post.get("node", {})

        post_id = node.get("id", "")
        username = node.get("owner", {}).get("username", "")
        likes = node.get("like_count", 0)
        comment_count = node.get("comments_count", 0)

        caption_data = node.get("caption", "")

        if isinstance(caption_data, dict):
            caption = caption_data.get("text", "")
        else:
            caption = caption_data or ""

        hashtags = re.findall(r"#\w+", caption)
        mentions = re.findall(r"@\w+", caption)

        writer.writerow([
            post_id,
            username,
            caption,
            ", ".join(hashtags),
            ", ".join(mentions),
            likes,
            comment_count
        ])

print("Dataset created successfully ✅")
print("Total rows written:", len(all_posts))

Dataset created successfully ✅
Total rows written: 120

In [69]:
df=pd.read_csv("instagram_dataset.csv")
df

,post_id,username,caption,hashtags,mentions,likes,comment_count
0,3757158876308143282_2091666763,indiancricketteam,𝐂.𝐇.𝐀.𝐌.𝐏.𝐈.𝐎.𝐍.𝐒 🏆\n\nCongratulations to #Tea...,"#TeamIndia, #WomenInBlue, #CWC25, #Final, #INDvSA",NaN,4736442,0
1,3584595824401203523_2091666763,indiancricketteam,𝗖. 𝗛. 𝗔. 𝗠. 𝗣. 𝗜. 𝗢. 𝗡. 𝗦! 🏆 🏆 🏆\n\nThe Rohit ...,"#TeamIndia, #ChampionsTrophy, #INDvNZ, #Final",NaN,6090099,0
2,3833711483344354403_2091666763,indiancricketteam,"Sixes, crucial catches, BIG IMPACT 😎\n\n🎥 Pres...","#TeamIndia, #T20WorldCup, #MenInBlue",NaN,130993,0
3,3833606553107385019_2091666763,indiancricketteam,A tale from one four-wicket haul to another ❤️...,"#TeamIndia, #AUSvIND",NaN,77500,0
4,3833545107770140826_2091666763,indiancricketteam,The Unfolding\n\nRaw. Real. Colombo.\n\n#TeamI...,"#TeamIndia, #T20WorldCup, #MenInBlue",NaN,233200,0
...,...,...,...,...,...,...,...
115,3827404635674336850_2091666763,indiancricketteam,There's another breakthrough ☝️\n\n🔝 work by I...,"#TeamIndia, #MenInBlue, #T20WorldCup, #INDvUSA",NaN,174721,0
116,3827391828803213350_376525195,icc,Arshdeep Singh gave India an early breakthroug...,#T20WorldCup,NaN,209689,0
117,3827388979922920451_376525195,icc,Rohit Sharma. Wankhede. #T20WorldCup Trophy in...,#T20WorldCup,NaN,2207672,0
118,3827389515141316940_2091666763,indiancricketteam,A successful powerplay 🙌\n\n#TeamIndia pick 3⃣...,"#TeamIndia, #MenInBlue, #T20WorldCup, #INDvUSA",NaN,272052,0
119,3827381664376993793_2091666763,indiancricketteam,Up and running with the ball 👊\n\nMohd. Siraj ...,"#TeamIndia, #MenInBlue, #T20WorldCup, #INDvUSA",NaN,196873,0

In [70]:
df.sample(5)

,post_id,username,caption,hashtags,mentions,likes,comment_count
62,3831438516069128981_440115170,asianpaints,"For every cheer, every hope,\nFor Har Ghar tha...",NaN,"@sunidhichauhan5, @vishaldadlani",96969,0
109,3827433518691881452_2091666763,indiancricketteam,Painting the ground with his masterful shot-ma...,"#TeamIndia, #MenInBlue, #T20WorldCup, #INDvUSA",NaN,143201,0
27,3833056420661378190_2091666763,indiancricketteam,4⃣ Overs\n2⃣2⃣ Runs\n4⃣ Wickets 🔥\n\nArundhati...,"#TeamIndia, #AUSvIND",NaN,75685,0
69,3831037335513357080_2091666763,indiancricketteam,Castled ⚡️⚡️\n\nJasprit Bumrah gets on the wic...,"#TeamIndia, #T20WorldCup, #MenInBlue, #INDvNAM",NaN,312180,0
108,3827747288501184594_2091666763,indiancricketteam,"When the captain calls, you answer 👌\n\n🎥 From...","#TeamIndia, #MenInBlue, #T20WorldCup, #INDvUSA",@mohammedsirajofficial,2432491,0